language: python

sudo: required

services:
  - docker

python:
  - "2.7"

before_install:
  # run cpascual/taurus-test docker container (Debian8 with taurus-deps and xvfb installed)
  - docker pull cpascual/taurus-test
  - docker run -d --name=taurus-test -h taurus-test --volume=`pwd`:/taurus cpascual/taurus-test
  - sleep 10
  
script:
  - docker exec taurus-test /bin/bash -c "cd taurus ; python setup.py install"
  - docker exec taurus-test /bin/bash -c "taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'"
